import {
  BarChart3,
  Boxes,
  Code2,
  Factory,
  Handshake,
  Landmark,
  LockKeyhole,
  ShieldCheck,
  UsersRound,
} from "lucide-react";

export const courses = [
  {
    slug: "sap-fico",
    short: "FICO",
    title: "SAP FICO",
    subtitle: "Finance & Controlling",
    description: "Master financial accounting, controlling, reporting, and real-world enterprise finance workflows.",
    schedule: {
      weekdays: { duration: "3 months", hours: "1 hour / day" },
      weekends: { duration: "10 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "10–12 weeks",
    level: "Beginner to Advanced",
    icon: Landmark,
    color: "#635bff",
    brochureUrl: "/assets/sv-curiotech-sap-fico-brochure.pdf",
    topics: ["General Ledger", "Accounts Payable", "Accounts Receivable", "Asset Accounting", "Cost Center Accounting", "Integration"],
  },
  {
    slug: "sap-mm",
    short: "MM",
    title: "SAP MM",
    subtitle: "Materials Management",
    description: "Build expertise in procurement, inventory, valuation, and end-to-end supply chain processes.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Beginner Friendly",
    icon: Boxes,
    color: "#08a88a",
    brochureUrl: "/assets/sv-curiotech-sap-mm-brochure.pdf",
    topics: ["Procure-to-Pay", "Inventory Management", "Vendor Master", "Material Master", "Pricing", "Invoice Verification"],
  },
  {
    slug: "sap-sd",
    short: "SD",
    title: "SAP SD",
    subtitle: "Sales & Distribution",
    description: "Learn order-to-cash, pricing, shipping, billing, and customer relationship processes.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Beginner Friendly",
    icon: BarChart3,
    color: "#ef7c35",
    brochureUrl: "/assets/sv-curiotech-sap-sd-brochure.pdf",
    topics: ["Sales Orders", "Pricing", "Delivery", "Shipping", "Billing", "Credit Management"],
  },
  {
    slug: "sap-pp",
    short: "PP",
    title: "SAP PP",
    subtitle: "Production Planning",
    description: "Plan production, optimize capacity, and understand manufacturing execution inside SAP.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Intermediate",
    icon: Factory,
    color: "#1689dd",
    topics: ["Master Data", "Demand Management", "MRP", "Capacity Planning", "Shop Floor Control", "Product Costing"],
  },
  {
    slug: "sap-abap",
    short: "ABAP",
    title: "SAP ABAP",
    subtitle: "Application Development",
    description: "Develop reports, interfaces, forms, enhancements, and modern SAP applications through code.",
    schedule: {
      weekdays: { duration: "3.5 months", hours: "1 hour / day" },
      weekends: { duration: "12 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "12–14 weeks",
    level: "Technical Track",
    icon: Code2,
    color: "#e64d86",
    topics: ["ABAP Basics", "Reports", "Data Dictionary", "Forms", "BAPIs & BADIs", "OData"],
  },
  {
    slug: "successfactors",
    short: "SF",
    title: "SAP SuccessFactors",
    subtitle: "Human Experience Management",
    description: "Configure cloud-based HR processes across employee central, performance, and recruiting.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Functional Track",
    icon: UsersRound,
    color: "#8b5cf6",
    topics: ["Employee Central", "Recruiting", "Onboarding", "Performance", "Compensation", "Analytics"],
  },
  {
    slug: "sap-ariba",
    short: "ARIBA",
    title: "SAP Ariba",
    subtitle: "Strategic Procurement",
    description: "Transform sourcing, procurement, supplier collaboration, and spend management in the cloud.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Functional Track",
    icon: Handshake,
    color: "#0aa3b5",
    topics: ["Sourcing", "Contracts", "Buying", "Invoicing", "Supplier Management", "Ariba Network"],
  },
  {
    slug: "sap-security",
    short: "SECURITY",
    title: "SAP Security",
    subtitle: "Authorization & Identity Management",
    description: "Learn user administration, roles, authorizations, access controls, and security operations across SAP systems.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Technical Track",
    icon: LockKeyhole,
    color: "#0f766e",
    topics: ["User Administration", "Role Design", "PFCG", "Authorization Objects", "SU24", "Security Auditing"],
  },
  {
    slug: "sap-grc",
    short: "GRC",
    title: "SAP GRC",
    subtitle: "Governance, Risk & Compliance",
    description: "Build practical skills in access governance, risk analysis, emergency access, compliance, and control monitoring.",
    schedule: {
      weekdays: { duration: "2.5 months", hours: "1 hour / day" },
      weekends: { duration: "10 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "10–12 weeks",
    level: "Technical / Functional Track",
    icon: ShieldCheck,
    color: "#b7791f",
    topics: ["Access Control", "Risk Analysis", "Access Request Management", "Emergency Access", "Business Role Management", "Process Control"],
  },
];

export const testimonials = [
  {
    name: "Priya Sharma",
    role: "SAP FICO Learner",
    company: "B.Com graduate",
    quote: "Before joining, I knew accounting but could not connect it with SAP screens. The vendor invoice, payment, and GL examples made FICO much easier to explain.",
    initials: "PS",
  },
  {
    name: "Karthik R.",
    role: "SAP MM Learner",
    company: "Stores and purchase background",
    quote: "The trainer connected purchase requisition, PO, goods receipt, and invoice verification with real procurement work. That helped me understand the full flow instead of separate steps.",
    initials: "KR",
  },
  {
    name: "Sneha Patil",
    role: "SAP SuccessFactors Learner",
    company: "HR operations",
    quote: "Employee Central and recruitment topics were explained with HR process examples. The resume review also helped me write my HR and SAP experience more clearly.",
    initials: "SP",
  },
  {
    name: "Ananya Rao",
    role: "SAP FICO Learner",
    company: "Finance background",
    quote: "The FICO classes connected journal entries, accounts payable, receivables, and reporting with SAP document flow. I stopped memorizing and started understanding the process.",
    initials: "AR",
  },
  {
    name: "Rahul Nair",
    role: "SAP MM Learner",
    company: "Procurement track",
    quote: "Material master, vendor master, inventory movement, and invoice verification were explained patiently. The practice tasks made revision much easier before interviews.",
    initials: "RN",
  },
  {
    name: "Megha S.",
    role: "Working Professional",
    company: "Weekend batch learner",
    quote: "The weekend batch worked well with my office schedule. I liked that interview questions were discussed after each topic, so revision felt connected to the course.",
    initials: "MS",
  },
  {
    name: "Vikram K.",
    role: "Career Switcher",
    company: "Non-IT background",
    quote: "I joined without SAP experience. The trainer started with ERP basics and slowly moved into business scenarios, which made the learning comfortable for me.",
    initials: "VK",
  },
  {
    name: "Nikhil Jain",
    role: "SAP ABAP Learner",
    company: "Technical track",
    quote: "Reports, debugging, internal tables, and data dictionary concepts became clearer because we practiced code regularly instead of only watching theory.",
    initials: "NJ",
  },
  {
    name: "Divya Menon",
    role: "SAP SD Learner",
    company: "Sales & distribution",
    quote: "The order-to-cash process was explained using sales order, delivery, billing, and pricing examples. It helped me answer scenario questions with better confidence.",
    initials: "DM",
  },
  {
    name: "Aishwarya M.", role: "SAP FICO Learner", company: "Commerce graduate",
    quote: "The practical posting exercises helped me connect accounting concepts with SAP configuration. The trainer repeated difficult topics until the logic became clear.", initials: "AM",
  },
  {
    name: "Naveen Kumar", role: "SAP MM Learner", company: "Procurement background",
    quote: "Working through the complete procure-to-pay cycle helped me explain purchasing and inventory scenarios more confidently during mock interview practice.", initials: "NK",
  },
  {
    name: "Roshni D.", role: "SAP SD Learner", company: "Sales operations",
    quote: "Pricing, delivery, billing, and customer master topics were taught with simple business examples. The course was useful because every step had a reason.", initials: "RD",
  },
  {
    name: "Shruthi R.", role: "SAP ABAP Learner", company: "Engineering fresher",
    quote: "Hands-on reports, debugging tasks, and small coding assignments helped me move from basic syntax to practical ABAP development with less fear.", initials: "SR",
  },
  {
    name: "Pradeep H.", role: "SAP PP Learner", company: "Mechanical graduate",
    quote: "Production planning became clearer when BOM, routing, work centers, and MRP were taught as one connected manufacturing process.", initials: "PH",
  },
  {
    name: "Keerthi S.", role: "Weekend Batch Learner", company: "Working professional",
    quote: "The weekend schedule and revision support helped me learn consistently while working full time. Doubts were cleared without making the class feel rushed.", initials: "KS",
  },
  {
    name: "Manjunath P.", role: "Beginner SAP Learner", company: "Career switcher",
    quote: "The counselling call helped me choose the right module before joining. After that, the step-by-step teaching made SAP feel approachable as a beginner.", initials: "MP",
  },
  {
    name: "Farah Khan", role: "Live Online Batch", company: "SAP learner",
    quote: "The online classes were interactive, with live demonstrations and regular assignments. I could ask doubts during class, which made a big difference.", initials: "FK",
  },
  {
    name: "Rakesh J.", role: "Interview Preparation Learner", company: "Job seeker",
    quote: "Mock interviews and project explanation practice showed me how to present my SAP knowledge in a structured way instead of giving memorized answers.", initials: "RJ",
  },
  {
    name: "Neha G.",
    role: "SAP FICO Learner",
    company: "Accounts executive",
    quote: "I was already working in accounts, but SAP terminology was new for me. The AP, AR, and bank accounting examples helped me relate the course to my daily work.",
    initials: "NG",
  },
  {
    name: "Sandeep M.",
    role: "SAP BASIS Learner",
    company: "IT support background",
    quote: "The BASIS sessions explained users, clients, transports, and basic administration in a practical way. It gave me a clearer path from IT support to SAP support.",
    initials: "SM",
  },
  {
    name: "Lavanya P.",
    role: "SAP SuccessFactors Learner",
    company: "MBA HR",
    quote: "The trainer explained cloud HR concepts using employee data, recruiting, onboarding, and performance examples. It helped me understand where HR work fits in SAP.",
    initials: "LP",
  },
  {
    name: "Mohammed Irfan",
    role: "SAP SD Learner",
    company: "Sales operations",
    quote: "Order-to-cash was taught with customer master, pricing, delivery, and billing examples. The scenario discussions helped me prepare better.",
    initials: "MI",
  },
  {
    name: "Pooja K.",
    role: "SAP Ariba Learner",
    company: "Supply chain fresher",
    quote: "Sourcing, supplier management, and procurement flow were explained in simple language. I liked that the trainer connected Ariba with real purchase processes.",
    initials: "PK",
  },
  {
    name: "Harish V.",
    role: "SAP Security Learner",
    company: "System admin background",
    quote: "Role design, authorizations, and user administration became clearer when we practiced common access scenarios. The examples felt close to real support work.",
    initials: "HV",
  },
  {
    name: "Kavya S.",
    role: "SAP SuccessFactors Learner",
    company: "HR background",
    quote: "The HR process explanation was clear, especially employee data, recruiting, and performance flow. It gave me a better idea of cloud HR careers.",
    initials: "KS",
  },
  {
    name: "Abhishek T.",
    role: "SAP GRC Learner",
    company: "Audit and compliance",
    quote: "Access risk, firefighter, and approval workflow topics were explained with compliance examples. That helped me connect my audit background with SAP GRC.",
    initials: "AT",
  },
  {
    name: "Ritika B.",
    role: "SAP FICO Learner",
    company: "MBA Finance",
    quote: "The course helped me understand how finance, procurement, and sales create postings in SAP. Integration examples were the most useful part for me.",
    initials: "RB",
  },
  {
    name: "Deepak C.",
    role: "SAP ABAP Learner",
    company: "BCA graduate",
    quote: "The ABAP assignments were practical and small enough to complete after class. Debugging practice helped me understand mistakes instead of depending only on notes.",
    initials: "DC",
  },
  {
    name: "Shalini V.",
    role: "SAP MM Learner",
    company: "Inventory management",
    quote: "Inventory movement types and valuation were confusing at first. After the trainer connected them with stock and invoice examples, the topic became manageable.",
    initials: "SV",
  },
  {
    name: "Arjun Rao",
    role: "SAP PP Learner",
    company: "Production planning trainee",
    quote: "The PP classes matched my mechanical background well. MRP, production order, and shop-floor examples helped me understand the consultant role better.",
    initials: "AR",
  },
  {
    name: "Meera N.",
    role: "SAP FICO Learner",
    company: "Career returner",
    quote: "I had taken a career break, so I needed patient teaching. The revision sessions and interview preparation helped me rebuild confidence gradually.",
    initials: "MN",
  },
  {
    name: "Girish B.",
    role: "SAP Security Learner",
    company: "Access management",
    quote: "The trainer explained why users need specific roles and how authorization issues are checked. It was useful for understanding real ticket scenarios.",
    initials: "GB",
  },
  {
    name: "Tanvi R.",
    role: "SAP SD Learner",
    company: "MBA marketing",
    quote: "I could connect sales concepts with SAP after seeing customer master, sales order, delivery, and billing together. The flow-based teaching helped a lot.",
    initials: "TR",
  },
  {
    name: "Vinay S.",
    role: "SAP MM Learner",
    company: "Warehouse operations",
    quote: "The course helped me understand how warehouse and procurement activities are recorded in SAP. The examples were practical and easy to revise.",
    initials: "VS",
  },
  {
    name: "Sahana L.",
    role: "SAP FICO Learner",
    company: "M.Com student",
    quote: "GL, AP, AR, and asset accounting were taught from basic accounting logic first. That made SAP screens less confusing when we moved to practice.",
    initials: "SL",
  },
  {
    name: "Yogesh K.",
    role: "SAP ABAP Learner",
    company: "Junior developer",
    quote: "The trainer explained reports, tables, debugging, and enhancements with examples I could try myself. It felt like proper development practice.",
    initials: "YK",
  },
];
