import {
  BarChart3,
  Boxes,
  Code2,
  Factory,
  Handshake,
  Landmark,
  LockKeyhole,
  ShieldCheck,
  UsersRound,
} from "lucide-react";

export const courses = [
  {
    slug: "sap-fico",
    short: "FICO",
    title: "SAP FICO",
    subtitle: "Finance & Controlling",
    description: "Master financial accounting, controlling, reporting, and real-world enterprise finance workflows.",
    schedule: {
      weekdays: { duration: "3 months", hours: "1 hour / day" },
      weekends: { duration: "10 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "10–12 weeks",
    level: "Beginner to Advanced",
    icon: Landmark,
    color: "#635bff",
    brochureUrl: "/assets/sv-curiotech-sap-fico-brochure.pdf",
    topics: ["General Ledger", "Accounts Payable", "Accounts Receivable", "Asset Accounting", "Cost Center Accounting", "Integration"],
  },
  {
    slug: "sap-mm",
    short: "MM",
    title: "SAP MM",
    subtitle: "Materials Management",
    description: "Build expertise in procurement, inventory, valuation, and end-to-end supply chain processes.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Beginner Friendly",
    icon: Boxes,
    color: "#08a88a",
    brochureUrl: "/assets/sv-curiotech-sap-mm-brochure.pdf",
    topics: ["Procure-to-Pay", "Inventory Management", "Vendor Master", "Material Master", "Pricing", "Invoice Verification"],
  },
  {
    slug: "sap-sd",
    short: "SD",
    title: "SAP SD",
    subtitle: "Sales & Distribution",
    description: "Learn order-to-cash, pricing, shipping, billing, and customer relationship processes.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Beginner Friendly",
    icon: BarChart3,
    color: "#ef7c35",
    brochureUrl: "/assets/sv-curiotech-sap-sd-brochure.pdf",
    topics: ["Sales Orders", "Pricing", "Delivery", "Shipping", "Billing", "Credit Management"],
  },
  {
    slug: "sap-pp",
    short: "PP",
    title: "SAP PP",
    subtitle: "Production Planning",
    description: "Plan production, optimize capacity, and understand manufacturing execution inside SAP.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Intermediate",
    icon: Factory,
    color: "#1689dd",
    topics: ["Master Data", "Demand Management", "MRP", "Capacity Planning", "Shop Floor Control", "Product Costing"],
  },
  {
    slug: "sap-abap",
    short: "ABAP",
    title: "SAP ABAP",
    subtitle: "Application Development",
    description: "Develop reports, interfaces, forms, enhancements, and modern SAP applications through code.",
    schedule: {
      weekdays: { duration: "3.5 months", hours: "1 hour / day" },
      weekends: { duration: "12 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "12–14 weeks",
    level: "Technical Track",
    icon: Code2,
    color: "#e64d86",
    topics: ["ABAP Basics", "Reports", "Data Dictionary", "Forms", "BAPIs & BADIs", "OData"],
  },
  {
    slug: "successfactors",
    short: "SF",
    title: "SAP SuccessFactors",
    subtitle: "Human Experience Management",
    description: "Configure cloud-based HR processes across employee central, performance, and recruiting.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Functional Track",
    icon: UsersRound,
    color: "#8b5cf6",
    topics: ["Employee Central", "Recruiting", "Onboarding", "Performance", "Compensation", "Analytics"],
  },
  {
    slug: "sap-ariba",
    short: "ARIBA",
    title: "SAP Ariba",
    subtitle: "Strategic Procurement",
    description: "Transform sourcing, procurement, supplier collaboration, and spend management in the cloud.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Functional Track",
    icon: Handshake,
    color: "#0aa3b5",
    topics: ["Sourcing", "Contracts", "Buying", "Invoicing", "Supplier Management", "Ariba Network"],
  },
  {
    slug: "sap-security",
    short: "SECURITY",
    title: "SAP Security",
    subtitle: "Authorization & Identity Management",
    description: "Learn user administration, roles, authorizations, access controls, and security operations across SAP systems.",
    schedule: {
      weekdays: { duration: "2 months", hours: "1 hour / day" },
      weekends: { duration: "8 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "8–10 weeks",
    level: "Technical Track",
    icon: LockKeyhole,
    color: "#0f766e",
    topics: ["User Administration", "Role Design", "PFCG", "Authorization Objects", "SU24", "Security Auditing"],
  },
  {
    slug: "sap-grc",
    short: "GRC",
    title: "SAP GRC",
    subtitle: "Governance, Risk & Compliance",
    description: "Build practical skills in access governance, risk analysis, emergency access, compliance, and control monitoring.",
    schedule: {
      weekdays: { duration: "2.5 months", hours: "1 hour / day" },
      weekends: { duration: "10 weekends", hours: "3 hours / day" },
      mode: "Live web / Classroom",
    },
    duration: "10–12 weeks",
    level: "Technical / Functional Track",
    icon: ShieldCheck,
    color: "#b7791f",
    topics: ["Access Control", "Risk Analysis", "Access Request Management", "Emergency Access", "Business Role Management", "Process Control"],
  },
];

export const testimonials = [
  {
    name: "Priya Sharma",
    role: "SAP FICO Consultant",
    company: "Placed at a global IT firm",
    quote: "The live business scenarios changed everything. I entered as a fresher and left interviews speaking like a consultant.",
    initials: "PS",
  },
  {
    name: "Karthik R.",
    role: "SAP MM Associate",
    company: "Career transition",
    quote: "The trainers patiently connected every concept to real procurement work. The mock interviews gave me genuine confidence.",
    initials: "KR",
  },
  {
    name: "Sneha Patil",
    role: "SuccessFactors Analyst",
    company: "Placed after course completion",
    quote: "A practical, encouraging learning environment. The CV review and placement preparation were as valuable as the course.",
    initials: "SP",
  },
];
